import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma client output (prisma-client generator, output: src/generated).
    // Regenerated by `prisma generate`, so its eslint-disable banners go stale
    // and lint should not report on it at all.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
