// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load the project's actual env file (Next.js convention). The default
// `dotenv/config` only reads `.env`, which prisma init seeded with a placeholder
// Prisma Postgres URL. `.env.local` holds the real Supabase connection strings.
config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (generate/migrate) run best over the direct/session
    // pooler connection. The transaction pooler (DATABASE_URL, port 6543)
    // breaks Prisma Migrate with `prepared statement "s1" already exists` —
    // PgBouncer re-uses sessions across backend connections. The runtime app
    // is unaffected: src/lib/db/prisma.js reads DATABASE_URL itself.
    url:
      process.env["PRISMA_DIRECT_URL"] ||
      process.env["DIRECT_URL"] ||
      process.env["POSTGRES_URL_NON_POOLING"] ||
      process.env["DATABASE_URL"] ||
      process.env["POSTGRES_PRISMA_URL"],
  },
});
