// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load the project's actual env file (Next.js convention). The default
// `dotenv/config` only reads `.env`, which prisma init seeded with a placeholder
// Prisma Postgres URL. `.env.local` holds the real Supabase connection strings.
config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
